"""Re-exports for Dextra IR."""

from dextra.ir.dextra_ir import (
    Alloca,
    ArrayLit,
    BasicBlock,
    BinOp,
    Branch,
    Call,
    CondBranch,
    ConstBool,
    ConstFloat,
    ConstInt,
    ConstString,
    Function,
    GetElement,
    GetField,
    IRBuilder,
    Instruction,
    Load,
    Local,
    Module,
    Param,
    Return,
    SetElement,
    SetField,
    Store,
    StringLit,
    StructLit,
    Temp,
    Terminator,
    UnaryOp,
    Value,
)
from dextra.ir.lowering import IRLowering, lower_program
from dextra.ir.verifier import assert_module_valid, verify_module

__all__ = [
    "Alloca",
    "ArrayLit",
    "BasicBlock",
    "BinOp",
    "Branch",
    "Call",
    "CondBranch",
    "ConstBool",
    "ConstFloat",
    "ConstInt",
    "ConstString",
    "Function",
    "GetElement",
    "GetField",
    "IRBuilder",
    "IRLowering",
    "Instruction",
    "Load",
    "Local",
    "Module",
    "Param",
    "Return",
    "SetElement",
    "SetField",
    "Store",
    "StringLit",
    "StructLit",
    "Temp",
    "Terminator",
    "UnaryOp",
    "Value",
    "lower_program",
    # Verifier:
    "assert_module_valid",
    "verify_module",
]
